#!/usr/bin/env php
<?php
/**
 * Install jquery-ui archive into Dynacase context dir
 *
 * @author Anakeen 2012
 */

$WIFF_ROOT = getenv("WIFF_ROOT");
if ($WIFF_ROOT === false) {
    print "WIFF_ROOT environment variable is not set!\n";
    exit(1);
}

$WIFF_CONTEXT_ROOT = getenv("WIFF_CONTEXT_ROOT");
if ($WIFF_CONTEXT_ROOT === false) {
    print "WIFF_CONTEXT_ROOT environment variable not set!\n";
    exit(1);
}

set_include_path(get_include_path() . PATH_SEPARATOR . $WIFF_CONTEXT_ROOT . PATH_SEPARATOR . "$WIFF_ROOT/include");

include_once('WHAT/Lib.System.php');

$ck_tgz = $argv[1];
if ($ck_tgz === NULL) {
    print sprintf("Missing JQuery-Ui archive argument\n");
    exit(1);
}
$ck_tgz = realpath($ck_tgz);
if (!is_file($ck_tgz)) {
    print sprintf("JQuery-UI archive not found at '%s'\n", $ck_tgz);
    exit(1);
}

$ret = chdir($WIFF_CONTEXT_ROOT);
if ($ret === false) {
    print sprintf("Could not change directory to '%s'\n", $WIFF_CONTEXT_ROOT);
    exit(1);
}

$tmpfile = LibSystem::tempnam(null, 'jqueryui_untar');
if ($tmpfile === false) {
    print sprintf("Could not create temporary file\n");
    exit(1);
}

$tempdir = basename($tmpfile);
$ret = mkdir($tempdir);
if ($ret === false) {
    print sprintf("Could not create temporary directory '%s'\n", $tempdir);
    @unlink($tmpfile);
    exit(1);
}

// Unpack archive in tempdir
$cmd = sprintf('unzip %s -d %s > %s 2>&1', escapeshellarg($ck_tgz), escapeshellarg($tempdir),
    escapeshellarg($tmpfile));
system($cmd, $ret);

$output = file_get_contents($tmpfile);
@unlink($tmpfile);

if ($ret !== 0) {
    print sprintf("Error %s: %s\n", $cmd, $output);
    exit(1);
}

// Set directory/files rights
$cmd = sprintf('find %s -type d -exec chmod 0755 {} \; > /dev/null 2>&1', escapeshellarg($tempdir));
system($cmd, $ret);
if ($ret !== 0) {
    print sprintf("Error setting rights on directories\n");
    exit(1);
}
$cmd = sprintf('find %s -type f -exec chmod 0644 {} \; > /dev/null 2>&1', escapeshellarg($tempdir));
system($cmd, $ret);
if ($ret !== 0) {
    print sprintf("Error setting rights on files\n");
    exit(1);
}

// Search for a /jquery-ui/ subdir in the unpacked archive
$fh = opendir($tempdir);
if ($fh === false) {
    print sprintf("Error opening temporary directory '%s'\n", $tempdir);
    exit(1);
}

$jqui_subdir = false;
while (($file = readdir($fh)) !== false) {
    if (is_dir(sprintf("%s/%s", $tempdir, $file)) && preg_match("/^ui$/", $file)) {
        $jqui_subdir = $file;
        break;
    }
}
if ($jqui_subdir === false) {
    print sprintf("Could not find a valid jquery-ui subdir in '%s'\n", $tempdir);
    exit(1);
}
$jqui_subdir = 'lib/jquery-ui/devel-src';
// Create jquery-ui dir if it does not exists
if (!is_dir($jqui_subdir)) {
    $ret = mkdir($jqui_subdir);
    if ($ret === false) {
        print sprintf("Could not create '$jqui_subdir' directory\n");
        exit(1);
    }
}

// Copy new jquery-ui files over existing jquery-ui directory
$cmd = sprintf('cp -r %s/* %s', escapeshellarg($tempdir), escapeshellarg($jqui_subdir));
system($cmd, $ret);

if ($ret !== 0) {
    print sprintf("Error copying jquery-ui files (%s)\n", $cmd);
    exit(1);
}


$cmd = sprintf('cd %s/themes/base && mkdir -p original && mv jquery.ui.all.css original && cat jquery.ui.core.css jquery.ui.accordion.css jquery.ui.autocomplete.css jquery.ui.button.css jquery.ui.datepicker.css jquery.ui.dialog.css jquery.ui.menu.css jquery.ui.menubar.css jquery.ui.progressbar.css jquery.ui.resizable.css jquery.ui.selectable.css jquery.ui.slider.css jquery.ui.spinner.css jquery.ui.tabs.css jquery.ui.tooltip.css jquery.ui.theme.css > jquery.ui.all.css', escapeshellarg($jqui_subdir));
system($cmd, $ret);

if ($ret !== 0) {
    print sprintf("Error copying jquery-ui files (%s)\n", $cmd);
    exit(1);
}


// Cleanup tempdir
$cmd = sprintf('rm -Rf %s', escapeshellarg($tempdir));
system($cmd, $ret);

//Apply patch

$cmd = sprintf("patch %s/ui/jquery.ui.menu.js %s/patch/menu.patch", escapeshellarg(
    $jqui_subdir),
    escapeshellarg($jqui_subdir));

system($cmd);

exit(0);

?>
